Heading:
  default: "ClassicPress"
  max: 25
  description:
    en: "Text for the heading in the footer - you can use your site name for example - Max length 25 characters"
Blurb:
  default: "The business-focused CMS. Powerful. Versatile. Predictable."
  max: 180
  description:
    en: "Enter a short blurb about your community - Max length 180 characters"
Link_sections:
  type: list
  default: "About, Learn about ClassicPress|Support, Support for ClassicPress|Download, Download the latest version of ClassicPress"
  description:
    en: 'Add link sections. The ideal number of sections is six. One item per line in this order:<br> Text, title<br><b>Text:</b> what appears on in the footer<br><b>Title:</b> the text that appears when the item is hovered.'
Links:
  type: list
  default: "About, Feature Requests, https://petitions.classicpress.net/, blank|About, About ClassicPress, https://www.classicpress.net/about/, blank|About, Donate to ClassicPress, https://donate.classicpress.net/, blank|Support, Documentation, https://docs.classicpress.net/, blank|Support, Support Forum, https://forums.classicpress.net/c/support, self|Download, ClassicPress, https://www.classicpress.net/get-classicpress/#install-classicpress, blank|Download, Migration Plugin, https://www.classicpress.net/get-classicpress/#switch-to-classicpress, blank"
  description:
    en: 'Add links to link sections. One item per line in this order:<br>Parent, text, URL, target, title<br>It is a good idea to keep the number of links under each section similar<br><b>Parent:</b> the name of the parent section which this link shows under. Use the `text` value from the list above<br><b>Text:</b> the text that shows for this link<br><b>URL:</b> the path this item links to. You can use relative paths as well.<br><b>Target:</b> Choose whether this item will open in a new tab or in the same tab. Use blank to open the link in a new tab, or use self to open it in the same tab.<br><b>Title:</b> the text that shows when the link is hovered.'
Small_links:
  type: list
  default: "Privacy , https://forums.classicpress.net/privacy, self|Terms , https://forums.classicpress.net/tos, self|About , https://forums.classicpress.net/about, self|Committee, https://www.classicpress.net/about/, blank"
  description:
    en: "You can add small links at the bottom of the footer like Terms of Service and Privacy. One item per line in this order:<br>Text, URL, target<br><b>Text:</b> The text that shows for the small link<br><b>URL:</b> The path of the link<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab"
Social_links:
  type: list
  default: "Website, Website, https://classicpress.net, blank, globe|Twitter, Twitter, https://twitter.com/getclassicpress, blank, fab-twitter|GitHub, GitHub, https://github.com/ClassicPress, blank, fab-github|Slack, Slack, https://www.classicpress.net/join-slack/, blank, fab-slack|LinkedIn, Linkedin, https://linkedin.com/company/ClassicPress, blank, fab-linkedin|Facebook, Facebook, https://www.facebook.com/GetClassicPress/, blank, fab-facebook-square"
  description:
    en: "Enter the social links you'd like to add to the footer in this format:<br> provider, title, URL, target<br><b>Provider:</b> is the name of the provider like Facebook or Twitter<br><b>Title:</b> The text that shows when the link is hovered<br><b>URL:</b> The path you'd like the link to have<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab<br><b>Icon:</b> use a FontAwesome5 icon name (brand icons need a 'fab-' prefix)."
svg_icons:
  default: "fab-twitter|globe|fab-github|fab-slack|fab-linkedin|fab-facebook-square"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in the social links setting above. "
